// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Border } from "./Border";
import type { Position } from "./Position";

export type BoardError = { dangling_borders: Array<Border>, incorrect_galaxy_sizes: Array<Position>, centerless_cells: Array<Position>, cut_centers: Array<Position>, asymmetric_centers: Array<Position>, };
