// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Border } from "./Border";
import type { GalaxyCenter } from "./GalaxyCenter";

export type Objective = { centers: Array<GalaxyCenter>, walls: Array<Border>, };
