// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardError } from "./BoardError";
import type { Objective } from "./Objective";

/**
 * ```rust
 */
export type StateView = {
  vertical_borders: Array<Array<boolean>>;
  horizontal_borders: Array<Array<boolean>>;
  objective: Objective;
  error: BoardError | null;
  has_future: boolean;
  has_past: boolean;
};
